version: '3.8'

services:
  gpu-notebook:
    image: cschranz/gpu-jupyter:v1.10_cuda-12.9_ubuntu-24.04
    container_name: gpu-notebook

    ports:
      - "127.0.0.1:9000:8888"

    volumes:
      - C:/:/c

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - JUPYTER_TOKEN=localdev

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
